# -*- coding: utf-8 -*-
"""Unidad 3: IOLA Python para finanzas - Ejercicios API reqres.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XdW1mA4voLH8Os5DxSqPgqYwPxX_5rcg

##Ejercicio 1
Para este trabajo practico, usaremos la página https://reqres.in/
que nos ofrece endpoints con datos Fakes (falsos)

<br>
La consigna es ejecutar los diferentes casos de usos disponibles.
En todos los casos se deberá guardar la respuesta y analizar el status code y el cuerpo del mensaje cuando corresponda. Para cada una de las operaciones identificar qué status code es y cual es el significado del mismo asi tambien es deseable que puedan establecer casos de fallos para cuando devuelve un error.

# Puntos a realizar:

- 1. Registrar un usuario (intentar con uno que inventemos).
- 2. Registrar un usuario que inventamos pero pasandole un mal un nombre de clave erroneo, por ej "emai" en vez de "email".
- 3. Registrar un usuario predefinido.
- 4. Hacer login.
- 5. Crear un usuario.
- 6. Obtener una lista de usuarios.
- 7. Obtener un usuario específico (lamentablemente los datos que se pueden probar  son los que están previamente cargado por la gente del sitio).
- 8. Utilizar los valores que devuelven error con sus diferentes endpoints.
- 9. refactorizar lo previamente hecho y separar cuando se pueda en funciones.
"""





















"""### Posible solucion"""

import requests


body = {
"email": "test.screener@reqres.in",
"password": "come3pesos"
}

r = requests.post(f"https://reqres.in/api/register", data= body)
r.status_code

#2
import requests


body ={
    "emai": "eve.holt@reqres.in",
    "password": "pistol"
}
r = requests.post(f"https://reqres.in/api/register", data= body)
r.text

#2
import requests


body ={
    "email": "eve.holt@reqres.in",
    "password": "pistol"
}
r = requests.post(f"https://reqres.in/api/register", data= body)
r.text







# 4
import requests

body ={
    "email": "eve.holt@reqres.in",
    "password": "cityslicka"
}
r = requests.post(f"https://reqres.in/api/login", data= body)
r.text

"""## Ejercicio 2

Modelar una orden de compra de un activo a un precio determinado y a un endpoint x
"""











